openapi: 3.0.3
info:
  title: Social Ingat Prediction API
  description: This API leverages advanced AI model to analyze text and provide insights on the nature of the messages, helping to identify potentially harmful or inappropriate content.
  version: 1.0.0
  contact:
    email: me@t4bby.dev
    name: Tabby
  termsOfService: "https://ingat.social/terms_of_service"
servers:
  - url: https://api.ingat.social
paths:
  /predict:
    post:
      summary: Predict message
      operationId: predictMessage
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: Message to predict
                  example: I am happy
      responses:
        '200':
          description: The prediction result
          content:
            application/json:
              schema:
                type: object
                properties:
                  scores:
                    type: object
                    description: Prediction scores
                    example:
                      spam: 0.1
                      ham: 0.9
  /report:
    post:
      summary: Report a message
      operationId: reportMessage
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                spam:
                  type: boolean
                  description: Is the message is spam or not
                  example: true
                message:
                  type: string
                  description: Message to report
                  example: I am not a spam
                device_information:
                  type: string
                  description: For device identification purposes
                  example: 'Phone Model: iPhone 12, OS: iOS 14.5.1, App Version: 1.0.0'
      responses:
        '200':
          description: Success
